
export const sectionTabs = [
  { id: "dashboard", label: "Dashboard", iconKey: "dashboard" },
  { id: "contactContent", label: "Contact", iconKey: "contact" },
  { id: "team", label: "Team", iconKey: "team" },
  { id: "projects", label: "Projects", iconKey: "projects" },
  { id: "events", label: "Events", iconKey: "events" },
  { id: "services", label: "Services", iconKey: "services" },
  { id: "blogs", label: "Blogs", iconKey: "blogs" },
  { id: "contact", label: "Contact Resource", iconKey: "contactResource" },
];

export const emptyContent = {
  hero: { title: "", subtitle: "", image: "" },
  about: { text: "" },
  contact: { name: "", specialty: "", email: "", phone: "", instagram: "", location: "" },
  churchPhotography: [],
  eventPhotography: [],
  organizationalWork: [],
};

export const resourceConfigs = {
  team: {
    label: "Team",
    iconKey: "team",
    empty: {
      name: "",
      role: "",
      bio: "",
      image: "",
      linkedin: "",
      featured: false,
    },
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "bio", label: "Bio", type: "textarea", required: false },
      { name: "image", label: "Image (URL or Upload)", type: "image", required: false },
      { name: "linkedin", label: "LinkedIn URL", type: "url", required: false },
      { name: "featured", label: "Featured", type: "checkbox", required: false },
    ],
  },
  projects: {
    label: "Projects",
    iconKey: "projects",
    empty: {
      title: "",
      category: "",
      date: "",
      location: "",
      attendees: "",
      description: "",
      coverImage: "",
      tags: "",
      galleryJson: "[]",
    },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: false },
      { name: "date", label: "Date", type: "text", required: false },
      { name: "location", label: "Location", type: "text", required: false },
      { name: "attendees", label: "Attendees", type: "text", required: false },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "coverImage", label: "Cover Image (URL or Upload)", type: "image", required: false },
      { name: "tags", label: "Tags (comma separated)", type: "text", required: false },
      { name: "galleryJson", label: "Gallery JSON", type: "textarea", required: false },
    ],
  },
  events: {
    label: "Event",
    iconKey: "events",
    empty: { title: "", date: "", description: "", coverImage: "", featured: false },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "date", label: "Date", type: "text", required: false },
      { name: "description", label: "Description", type: "textarea", required: false },
      { name: "coverImage", label: "Cover Image (URL or Upload)", type: "image", required: false },
      { name: "featured", label: "Featured", type: "checkbox", required: false },
    ],
  },
  services: {
    label: "Service",
    iconKey: "services",
    empty: {
      title: "",
      tagline: "",
      price: "",
      description: "",
      features: "",
      highlighted: false,
    },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "tagline", label: "Tagline", type: "text", required: false },
      { name: "price", label: "Price", type: "text", required: false },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "features", label: "Features (comma separated)", type: "text", required: false },
      { name: "highlighted", label: "Highlighted", type: "checkbox", required: false },
    ],
  },
  blogs: {
    label: "Blog",
    iconKey: "blogs",
    empty: {
      title: "",
      category: "",
      date: "",
      readTime: "",
      excerpt: "",
      image: "",
      featured: false,
    },
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: false },
      { name: "date", label: "Date", type: "text", required: false },
      { name: "readTime", label: "Read Time", type: "text", required: false },
      { name: "excerpt", label: "Excerpt", type: "textarea", required: false },
      { name: "image", label: "Image (URL or Upload)", type: "image", required: false },
      { name: "featured", label: "Featured", type: "checkbox", required: false },
    ],
  },
  contact: {
    label: "Contact",
    iconKey: "contactResource",
    empty: { label: "", value: "" },
    fields: [
      { name: "label", label: "Label", type: "text", required: true },
      { name: "value", label: "Value", type: "text", required: true },
    ],
  },
};